# User config
author: "iStemLabs.Africa"
tagline: "inspaya.com Science, Technology, Engineering and Mathematics Labs Africa"
description: "Africa is known for it's vast natural resources. <br /><br />Less featured are it's numerous intellectuals, whose every day lives revolve around innovation used to address daily societal challenges. <br /><br />iStemLabsAfrica is designed to showcase the continent's intellectuals, share knowledge and mentor generations of innovators coming up."
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "info@inspaya.com"
linkedin: "https://www.linkedin.com/company/inspaya-com"
twitter: "https://twitter.com/inspaya"
github: "https://github.com/inspaya"

# Site config
baseurl: "/home"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed